### ISSUE TITLE
Gene Selection API needs/isssues

### ISSUE THREAD

**Issue by BobMiller** [cognoma/django-cognoma#20]
Here are the three methods the UI will use for the user to create the desired gene list. Each has its own data/API issues.

## **Gene Selection - direct selection**
User needs to select genes from list of 20,000 genes. User will enter the first few letters of the gene identifier, a listbox will be populated containing only genes matching those letters. 
Here are three possible options for doing this:

1. UI uses API requests full gene list (20,000), server sends it to UI. UI is responsible for filtering list to display. _This approach may tax UI resources, and be too slow for a smooth interface_.

2. UI uses API to request only genes starting with a string of letters, server returns a filtered list to UI. This process will happen multiple times as user thins list. _Quick response from the server is critical for smooth performance._

3. UI uses API to request full ordered gene list, server returns not only full list, but also an index of the list. The index will contain the stating location of every 2 letter combination. The UI would then use the index to quickly filter the full gene list and populate the listbox.

## **Gene Selection - selection by path**

In selection by path, a listbox is populated by known pathways, the user selects a path, a second listbox is populated containing only those genes associated with the selected path. The user then selects some or all of the desired genes from this second listbox. 

To initialize this screen, an API will be needed to request the path list. The server should return the list of know paths.

Once a user selects a path, an API is needed to request only those genes associated with this path. The server should return a gene list.

## **Gene Selection - custom query**

This is the least defined of the three gene selection methods. In this method, the UI will provide the user with a query building gui in which the user will construct a custom gene selection query. An API will submit the custom query/criteria to the server. The server will return a gene list.

**Comment by dcgoss** [comment]
Are we building out each of these methods, or are we choosing from one?

**Comment by dcgoss** [comment]
Also, in my experience the more you can offload to the backend/API the better off you will be. It's easier to develop, and the idea of sending 20,000 genes each request doesn't sound like the right solution. 

I would recommend any frontend updates to be done via a simple API request.

**Comment by dhimmel** [comment]
I'm guessing this issue is talking about selecting the genes for constructing mutation status (the outcome vector). We eventually will want to let users subset the genes to use features (from the expression dataset). However, this second task doesn't need as slick/advanced of a user interface.

If you want to make your life easy, you can start with the "direct selection" method. For this method, [`django-genes`](https://bitbucket.org/greenelab/django-genes) may already provide the necessary backend (CCing @cgreene and @rzelayafavila). For development, the frontend could always start with a small dummy set of genes.

**Comment by awm33** [comment]
I'm already incorporating django-genes models. We can add a search query parameter to search across the fields we want to use in "suggesting" genes in the input.

**Comment by cgreene** [comment]
I like the idea of suggesting genes for input instead of passing all
20,000. django-genes can work with an elasticsearch backend via
django-haystack to provide this capability.

Incorporating the gene-chooser via @dhimmel's hetnets would also be a
secondary method that allows researchers to use items other than gene
names, but this would probably work with calls out to neo4j.het.io instead
of our django-genes backend.

**Comment by BobMiller** [comment]
Thanks everybody for the feedback.

I just wanted to summarize what came out of the discussions between the front end and back end groups last week (Aug 23), and some of the subsequent discussions.

It looks like there is also a 4th method for Gene Selection that I did not mention above: Uploading a list of genes.  In this method the user has the option of uploading a list of genes. The list would be in text or other format. 

So the proposed methods of Gene Selection are

- Direct Selection
- Selection by Path
- Custom Query
- Upload List

First we are going to concentrate (as Dave, i.e. @dhimmel, suggested above)  on **Direct Selection**.  For now we will be tabling Selection by Path, Custom Query, and Upload List until we have the system working with the Direct Selection Method.

**To implement Direct Selection we will be using approach 2: "_UI uses API to request only genes starting with a string of letters, server returns a filtered list to UI_. ". So the front end will not be working with the full gene list, but a smaller filtered one provided from the back end via an API .** Andrew, i.e. @awm33, and the back end team are already working on providing an API.

On the front end portion of this project (https://github.com/cognoma/frontend/issues/10) @awm33, and @laszlokv have suggested some tools that could be used to create the Gene Selection page. I am currently using there suggestions to create a prototype of Gene Selection page. I should have something to post by our next meeting (Sept 6th).

Given the above I am going to close this issue. 

Thanks everyone for your help and comments,
